name: Docker Build and Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
      platforms:
        description: 'Target platforms'
        required: false
        default: 'linux/amd64,linux/arm64'
        type: choice
        options:
          - linux/amd64,linux/arm64
          - linux/amd64
          - linux/arm64

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tags
        id: tags
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # 手动触发：使用用户指定的标签
            TAG="${{ inputs.tag }}"
            if [ "$TAG" = "latest" ] && [ "${{ github.ref_name }}" != "main" ]; then
              TAG="manual-$(date +%Y%m%d-%H%M%S)"
            fi
          else
            # 自动触发：主分支使用latest
            TAG="latest"
          fi
          echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG" >> $GITHUB_OUTPUT
          echo "Generated tag: $TAG"

      - name: Get build info  
        id: build-info
        run: |
          echo "version=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "commit=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ inputs.platforms || 'linux/amd64,linux/arm64' }}
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            VERSION=${{ steps.build-info.outputs.version }}
            COMMIT=${{ steps.build-info.outputs.commit }}
            DATE=${{ steps.build-info.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image info
        run: |
          echo "Image pushed: ${{ steps.tags.outputs.tags }}"
          echo "Platforms: ${{ inputs.platforms || 'linux/amd64,linux/arm64' }}"
          echo "Version: ${{ steps.build-info.outputs.version }}"